SCT_TAGS_SPANISH = ["estructura corporal",
                    "célula",
                    "estructura celular",
                    "anomalía morfológica",
                    "hallazgo",
                    "trastorno",
                    "medio ambiente",
                    "localización geográfica",
                    "evento",
                    "entidad observable",
                    "organismo",
                    "fármaco de uso clínico",
                    "producto medicinal",
                    "forma farmacéutica de producto medicinal",
                    "objeto físico",
                    "producto",
                    "fuerza física",
                    "objeto físico",
                    "producto",
                    "procedimiento",
                    "régimen/tratamiento",
                    "régimen/terapia",
                    "calificador",
                    "método de administración",
                    "forma farmacéutica básica",
                    "disposición",
                    "forma farmacéutica",
                    "sitio de administración previsto",
                    "nombre de producto",
                    "forma de liberación",
                    "rol",
                    "estado de la materia",
                    "transformación",
                    "proveedor",
                    "unidad de presentación",
                    "elemento de registro",
                    "situación",
                    "atributo",
                    "metadato del núcleo",
                    "metadato fundacional",
                    "relación asertiva",
                    "concepto de enlace",
                    "espacio de nombres",
                    "concepto de metadatos de OWL",
                    "contexto social",
                    "grupo étnico",
                    "estilo de vida",
                    "ocupación",
                    "persona",
                    "grupo racial",
                    "religión/filosofía",
                    "concepto inactivo",
                    "concepto para navegación",
                    "espécimen",
                    "escala de estadificación",
                    "escala de evaluación",
                    "estadificación tumoral",
                    "sustancia"]

SCT_TAGS_ENGLISH = ["body structure",
                    "cell",
                    "cell structure",
                    "morphologic abnormality",
                    "finding",
                    "disorder",
                    "environment",
                    "geographic location",
                    "event",
                    "observable entity",
                    "organism",
                    "clinical drug",
                    "medicinal product",
                    "medicinal product form",
                    "physical object",
                    "product",
                    "physical force",
                    "physical object",
                    "product",
                    "procedure",
                    "regime/therapy",
                    "qualifier value",
                    "administration method",
                    "basic dose form",
                    "disposition",
                    "dose form",
                    "intended site",
                    "number",
                    "product name",
                    "release characteristic",
                    "role",
                    "state of matter",
                    "transformation",
                    "supplier",
                    "unit of presentation",
                    "record artifact",
                    "situation",
                    "attribute",
                    "core metadata concept",
                    "foundation metadata concept",
                    "link assertion",
                    "linkage concept",
                    "namespace concept",
                    "OWL metadata concept",
                    "social concept",
                    "ethnic group",
                    "life style",
                    "occupation",
                    "person",
                    "racial group",
                    "religion/philosophy",
                    "inactive concept",
                    "navigational concept",
                    "specimen",
                    "staging scale",
                    "assessment scale",
                    "tumor staging",
                    "substance"]

SCT_TAG_ES2EN = {"estructura corporal":"body structure",
                "célula":"cell",
                "estructura celular":"cell structure",
                "anomalía morfológica":"morphologic abnormality",
                "hallazgo":"finding",
                "trastorno":"disorder",
                "medio ambiente":"environment",
                "localización geográfica":"geographic location",
                "evento":"event",
                "entidad observable":"observable entity",
                "organismo":"organism",
                "fármaco de uso clínico":"clinical drug",
                "producto medicinal":"medicinal product",
                "forma farmacéutica de producto medicinal":"medicinal product form",
                "objeto físico":"physical object",
                "producto":"product",
                "fuerza física":"physical force",
                "objeto físico":"physical object",
                "producto":"product",
                "procedimiento":"procedure",
                "régimen/tratamiento":"regime/therapy",
                "calificador":"qualifier value",
                "método de administración":"administration method",
                "forma farmacéutica básica":"basic dose form",
                "disposición":"disposition",
                "forma farmacéutica":"dose form",
                "sitio de administración previsto":"intended site",
                "":"number",
                "nombre de producto":"product name",
                "forma de liberación":"release characteristic",
                "rol":"role",
                "estado de la materia":"state of matter",
                "transformación":"transformation",
                "proveedor":"supplier",
                "unidad de presentación":"unit of presentation",
                "elemento de registro":"record artifact",
                "situación":"situation",
                "atributo":"attribute",
                "metadato del núcleo":"core metadata concept",
                "metadato fundacional":"foundation metadata concept",
                "relación asertiva":"link assertion",
                "concepto de enlace":"linkage concept",
                "espacio de nombres":"namespace concept",
                "concepto de metadatos de OWL":"OWL metadata concept",
                "contexto social":"social concept",
                "grupo étnico":"ethnic group",
                "estilo de vida":"life style",
                "ocupación":"occupation",
                "persona":"person",
                "grupo racial":"racial group",
                "religión/filosofía":"religion/philosophy",
                "concepto inactivo":"inactive concept",
                "concepto para navegación":"navigational concept",
                "espécimen":"specimen",
                "escala de estadificación":"staging scale",
                "escala de evaluación":"assessment scale",
                "estadificación tumoral":"tumor staging",
                "sustancia":"substance",
                "función":"function",
                "concepto no activo":"inactive concept",
                "régimen/terapia":"regime/therapy",
                "medio ambiente / localización":"environment",
                "SNOMED RT+CTV3":"SNOMED RT+CTV3",
                "concepto especial": "special concept",
                "metadato":"core metadata concept",
                "categoría dependiente del contexto":"context-dependent category",
                "concepto administrativo":"administrative concept",
                }

ADDITIONAL_EN_SCT = ["function", # Mapped to "observable entity"
                     "context-dependent category",  #renamed to situation
                     "administrative concept", # mapped to "record artifact"
                     "SNOMED RT+CTV3", # ROOT of snomed
                     "special concept",
                     "metadata",
                     "biological function",
                     "environment / location"
                     ]
ADDITIONAL_ES_SCT = ["concepto no activo",
                     "función", # MApped to "entidad observable"
                     "categoría dependiente del contexto", #mapped a situacion
                     "concepto administrativo" , # mapped to "elemento de registro" "espacio de nombres"
                     "régimen/terapia", #same as to "regimen/tratamiento",
                     "medio ambiente / localización", # same as "medio ambiente/localización"
                     "SNOMED RT+CTV3", # ROOT of snomed
                     "concepto especial", 
                     "metadato"
                     ]